### ISSUE TITLE
mod升级到1.3.3后加载投影时游戏崩溃

### ISSUE THREAD

**Issue by snpdzk** [Fallen-Breath/litematica-server-paster#10]
### Bug description

游戏崩溃

### Steps to reproduce

加载原理图-选择投影-加载原理图-游戏崩溃

### Relevant logs

https://mclo.gs/jfMXg1H

### Minecraft version

1.20.1

### Litematica Server Paster version

1.3.3

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment]
请确保此 issue 与本模组相关，比如创建最小复现环境并尝试复现此 issue。注意所提供的日志里最后一个发生于 18:19:15 的错误与本模组无关

**Comment by snpdzk** [comment]
仅有fabric-api 0.92.2，malilib 0.16.3，litematica 0.15.3，litematica server paster 1.3.2不会崩溃，升级到1.3.3出现崩溃
1.3.3日志：https://mclo.gs/rGZU8zO
1.3.2日志：https://mclo.gs/EK9JzZ8
