### ISSUE TITLE
NBT restore can't run

### ISSUE THREAD

**Issue by vocaloidkiss** [Fallen-Breath/litematica-server-paster#2]
### Bug description

服务器和客户端均使用1.20.1最新版，但双端安装，正确设置后仍无法使用，无法在服务器粘贴箱子里的物品

### Steps to reproduce

服务器和客户端均使用1.20.1最新版，但双端安装，正确设置后仍无法使用，无法在服务器粘贴箱子里的物品

### Expected behavior

服务器和客户端均使用1.20.1最新版，但双端安装，正确设置后仍无法使用，无法在服务器粘贴箱子里的物品

### Actual behavior

服务器和客户端均使用1.20.1最新版，但双端安装，正确设置后仍无法使用，无法在服务器粘贴箱子里的物品

### Minecraft version

1.20.1

### Litematica Server Paster version

1.2.3

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by vocaloidkiss** [comment]
无法获取服务器实体方块的数据，很离谱

**Comment by vocaloidkiss** [comment]
希望能写明白，而不是单纯说服务端粘贴，这谁能看得出来

**Comment by Fallen-Breath** [comment]
请组织你的语言表述，用清晰明确的语句阐述本 issue，包括 bug 的描述、复现步骤、期望表现、实际表现，而非使用含糊不清上下文不连贯的语句在这里宣泄情绪

----

> NBT restore can't run

对于这个标题，我并未在 issue 描述中见到与其相关的表述

> 服务器和客户端均使用1.20.1最新版，但双端安装，正确设置后仍无法使用，无法在服务器粘贴箱子里的物品

请给出足够详细的上下文信息以供复现。如果只有这一句话，那么将会得到“无法复现”的回复

> 无法获取服务器实体方块的数据，很离谱

本 mod 并无获取服务器方块实体的功能

> 希望能写明白，而不是单纯说服务端粘贴，这谁能看得出来

写明白什么，想要人看清什么，请说明白

**Comment by vocaloidkiss** [comment]
服务器安装了plusls carpet addition, 
输入了/carpet setDefault pcaSyncProtocol true开启了pca协议
在masa gadget中litematica一栏中打开了服务器中保存投影保存容器数据选项
上述这些mod版本互相均无冲突，
服务器端，客户端均安装了目前最新版litematica-sever-paster
Fabric API.和fabricloader安装了目前的最新版本
litematica设置粘贴NBT迁移选项为none
设置使用小木斧指令为false
服务器不禁用summon，setblock
我的权限等级为4。

在上述不禁用指令，有权限，所需选项协议全部开启的服务器中，我放置一个内含物品的箱子，保存原理图，再将原理图放置在世界上其他位置，粘贴，得到箱子内部是空的结果。
将上述保存的原理图，放置到一个本地游戏中，粘贴，箱子内部有物品。

新建本地游戏，用投影在本地再保存一个含有物品的容器原理图，在服务器端可以粘贴出容器内物品。

希望可以支持粘贴从服务器中保存的投影，因为它可以在本地正常粘贴。

在github对于该模组的介绍中， 无法看出该模组仅能保存本地原理图后粘贴到服务器，
而不能在服务器保存原理投放粘贴到服务器。

**Comment by vocaloidkiss** [comment]
我已经发现问题，在服务器中，如果不打开容器，无法通过pca同步，原理图也没有数据。。。
建议更改github的模组介绍
这个issue可以关闭了。。

**Comment by Fallen-Breath** [comment]
从服务端保存带容器的原理图，并非本 mod 的功能。若涉及其他 mod，则本 issue 与本 mod 无关

关于“原理图需要含有容器内容，才可贴出容器”，这是 litematica mod 的基础使用知识，并不是本 mod 的 README 该说明的。本模组的 README 只需做好其本职工作

**Comment by vocaloidkiss** [comment]
注意，作者为使用本mod者提供常见问题的勘误应当被重视，尤其是有问题反馈之后。
说明应当是更加人性化的，例如：介绍中说明玩家遇到某问题可以前往litematica在github上的wiki查阅。
至少目前的社区环境而言，并非所有人都是高认知，高自觉，高搜索嗅觉的。

**Comment by vocaloidkiss** [comment]
是否可以认为，开发模组时仅考虑目标玩家&开发者，而不需要考虑其他非专业玩家的反馈？

**Comment by vocaloidkiss** [comment]
仍然感谢作者的说明，我并不觉得作者需要作出任何改变

**Comment by Fallen-Breath** [comment]
> 是否可以认为，开发模组时仅考虑目标玩家&开发者，而不需要考虑其他非专业玩家的反馈

请不要以偏概全。本模组并不提供面向 0 基础小白的全套包会教程，但依然提供任何人可以访问的 issue 页面
