### ISSUE TITLE
Hello, I'm asking you to make fabric or quilt for version 1.20.2 on modrinth, thank you very much!

### ISSUE THREAD

**Issue by verixyt3** [Fallen-Breath/litematica-server-paster#3]
### Motivation

Hello, I'm asking you to make fabric or quilt for version 1.20.2 on modrinth, thank you very much!

### Description

Hello, I'm asking you to make fabric or quilt for version 1.20.2 on modrinth, thank you very much!

### Other information

Hello, I'm asking you to make fabric or quilt for version 1.20.2 on modrinth, thank you very much!

**Comment by Fallen-Breath** [comment]
litematica itself does not support 1.20.2 yet, so please be patient and wait

**Comment by yhw2003** [comment]
> litematica itself does not support 1.20.2 yet, so please be patient and wait

投影mod本身已经支持了...催更喵

**Comment by yhw2003** [comment]
> litematica itself does not support 1.20.2 yet, so please be patient and wait

net.minecraft.network.packet.s2c.play.CustomPayloadS2CPacket这个类在1.20.2被ojang删了，移植可能需要不少工作

**Comment by Fallen-Breath** [comment]
Added suppport for mc1.20.2 in [v1.2.0](https://github.com/Fallen-Breath/litematica-server-paster/tree/v1.2.0)
