### ISSUE TITLE
关于1.20.4的releases

### ISSUE THREAD

**Issue by Crystal0404** [Fallen-Breath/litematica-server-paster#4]
只是来确认一下，是不是忘记发布1.20.4的releases, 我构建了dev分支，它似乎一切正常

**Comment by sakura-ryoko** [comment]
https://github.com/Fallen-Breath/litematica-server-paster/tree/dev

But as a DEV tree, you'd have to self-build it.

**Comment by Skywind5487** [comment]
不好意思，请问要怎么build呢?
或者何时会有1.20.4的release?

**Comment by Crystal0404** [comment]
> 不好意思，请问要怎么build呢? 或者何时会有1.20.4的release?

fork仓库，运行release工作流

**Comment by Skywind5487** [comment]
但是release似乎需要自己上传执行档或jar?
我现在似乎没有办法获得?

**Comment by Crystal0404** [comment]
> 但是release似乎需要自己上传执行档或jar? 我现在似乎没有办法获得?

https://github.com/Crystal0404/litematica-server-paster/releases

**Comment by Skywind5487** [comment]
thank you very much!!!
