### ISSUE TITLE
Kicked for spamming 1.20.4

### ISSUE THREAD

**Issue by rhodso** [Fallen-Breath/litematica-server-paster#5]
### Bug description

I have this on my server, but my friend still gets kicked for spamming. I built the project from commit e130050 on the master branch (latest commit at time of writing, only one that appears to support 1.20.4), put the mod on the server and my friend's client, and it doesn't seem to have an effect. They are still kicked for spamming.

### Steps to reproduce

1. Build the project from commit e130050 on master branch
2. Put the jar in the mods folder on a Fabric server
3. Add the mod to the client
4. As a non-opped player, try to paste something with litematica

### Expected behavior

The schematic is placed as normal

### Actual behavior

Player is kicked for spamming

### Relevant logs

```
[23:39:25] [Server thread/INFO]: FriendsMcAcct[/FriendsIP] logged in with entity id 1200 at (39.10645949282788, 81.01670875107095, 342.46233236649744)
[23:39:25] [Server thread/INFO]: FriendsMcAcct joined the game
[23:39:25] [Netty Epoll Server IO #11/INFO]: Player FriendsMcAcct connected with Litematica Server Paster @ 1.2.0-SNAPSHOT
[23:42:42] [Server thread/INFO]: FriendsMcAcct lost connection: Kicked for spamming
[23:42:42] [Server thread/INFO]: FriendsMcAcct left the game
```
Here, FriendsMcAcct is my friend's account and FriendsIP is their IP

### Minecraft version

1.20.4

### Litematica Server Paster version

1.2.0 (Built from commit e130050 on master)

### Other information

This isn't an issue for me as I am opped on the server

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment]
Vanilla Minecraft itself implements some kind of chat antispamming feature. If litematica itself doesn't handle that, then 

Try pasting without this mod, the player might still be kicked

**Comment by rhodso** [comment]
The player still gets kicked without the mod installed. I tried changing Litematica's setting to only allow 3 commands per second, which seemed reasonable, but was still encountering issues. 

I only thought about trying this mod to fix this issue.

**Comment by Fallen-Breath** [comment]
In vanilla Minecraft, you can only send 1 message per second (with an extra 10 messages tolerance) without being kicked for spam. To bypass this, you can either give the player op, or use another mod to bypass the spam check (e.g. Carpet TIS Addition's rule `antiSpamDisabled`)

Also, as this is not litematica-server-paster's issue, I'm closing this issue
