### ISSUE TITLE
Unable to join server with ViaFabric due to `Internal Exception: net.minecraft.class_148: Loading NBT data` error

### ISSUE THREAD

**Issue by MrPiperdine** [Fallen-Breath/litematica-server-paster#6]
### Bug description

When using this mod along with ViaFabric on both client and server, players can't join the server, while client **with only litematica** but **without litematica-server-paster** can.
![捕获](https://github.com/Fallen-Breath/litematica-server-paster/assets/128112694/ff329238-d246-4b2b-8f43-3e1b0cd57b25)

### Steps to reproduce

1. launch 1.18.2 fabric server with latest ViaFabric and litematica-server-paster
2. launch 1.20.4 client with  latest ViaFaric and litematica, player can join the server normally
3. add latest litematica-server-paster and restart the client, player can't  join the server due to `Internal Exception: net.minecraft.class_148: Loading NBT data` error

### Expected behavior

client with both litematica-server-paster and litematica can join server with ViaFabric normally, as players in survival may use other litematica features

#### Server log
https://mclo.gs/bZtPxwt
#### Client log
https://mclo.gs/Tc9XKwY

### Minecraft version

server: 1.18.2, client: 1.20.4

### Litematica Server Paster version

v1.2.1

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment]
Vanilla changes the nbt network payload format in mc 1.20.2, and translator mods like viaversion do not know how to translate data inside mod packets

Please make sure both of your client / server versions are below or above 1.20.2 before using mods with custom network packets, or such disconnection will happen

**Comment by MrPiperdine** [comment]
Thanks for the explanation! I'll recommend players to use client with a matching version instead
