### ISSUE TITLE
The link to 1.21-sakura.4 version of Litematica leads to 404 not found.

### ISSUE THREAD

**Issue by xunfengawa** [Fallen-Breath/litematica-server-paster#7]
The link to Litematica in the 1.21 release [1.21-sakura.4](https://github.com/sakura-ryoko/litematica/releases/tag/1.21-sakura.4) leads to 404 not found.

Suppose the updated link should be: [1.21-sakura.6](https://github.com/sakura-ryoko/litematica/releases/tag/1.21-sakura.6)

**Comment by Fallen-Breath** [comment]
It was there yesterday tho. Whatever, I'll just place a [release page url](https://github.com/sakura-ryoko/litematica/releases) there, in case the .6 version gets deleted in the future
